# Generated by Django 6.1 on 2026-08-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In (Purchase/Restock)'), ('OUT', 'Stock Out (Sale/Dispatch)')], max_length=10),
        ),
    ]
