# Generated by Django 6.1 on 2026-08-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='password_change_required',
            field=models.BooleanField(default=False),
        ),
    ]
